// Run with `npm test`. Replays the server's golden messages (generated by the
// librqbit list_feed tests from real list responses with generic names) and checks
// the result against the full `/torrents?with_stats=true` responses.
import snapshotsFile from "../../../src/list_feed/testdata/list_snapshots.json";
import messagesFile from "../../../src/list_feed/testdata/list_messages.json";
import {
  FeedClient,
  FeedMessage,
  applyPatch,
  formatEta,
  formatSpeed,
} from "./listFeed";

let failures = 0;
let checks = 0;
function eq(actual: unknown, expected: unknown, what: string) {
  checks++;
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a !== e) {
    failures++;
    console.error(
      `FAIL ${what}:\n got  ${a.slice(0, 400)}\n want ${e.slice(0, 400)}`,
    );
  }
}

/** Sorted keys, no nulls, without the fields the feed drops. */
function normalize(v: any): any {
  if (Array.isArray(v)) return v.map(normalize);
  if (v === null || typeof v !== "object") return v;
  const out: any = {};
  for (const k of Object.keys(v).sort()) {
    if (v[k] === null) continue;
    if (
      [
        "average_piece_download_time",
        "downloaded_and_checked_bytes",
        "total_piece_download_ms",
        "live_tcp",
        "live_utp",
        "live_socks",
        "live_seeders",
        "steals",
      ].includes(k)
    )
      continue;
    out[k] = normalize(v[k]);
  }
  return out;
}

const snapshots = (snapshotsFile as any).snapshots as { torrents: any[] }[];
const messages = (messagesFile as any).messages as FeedMessage[];

// Snapshot + deltas == full state, at every step.
const c = new FeedClient();
messages.forEach((m, i) => {
  eq(c.apply(m), "ok", `apply message ${i}`);
  eq(c.seq, i + 1, `seq after ${i}`);
  const got = c.torrents();
  const want = snapshots[i].torrents;
  eq(
    got.map((t) => t.id),
    want.map((t) => t.id),
    `order at ${i}`,
  );
  eq(normalize(got), normalize(want), `state ${i} equals the full response`);
  // Exact human-readable strings and the nulls the UI checks.
  got.forEach((t, j) => {
    const w = want[j];
    eq(t.name, w.name ?? null, `name ${i}/${j}`);
    eq(t.stats?.error, w.stats.error, `error ${i}/${j}`);
    eq(
      t.stats?.live?.download_speed,
      w.stats.live?.download_speed,
      `download_speed ${i}/${j}`,
    );
    eq(
      t.stats?.live?.time_remaining ?? null,
      w.stats.live?.time_remaining ?? null,
      `eta ${i}/${j}`,
    );
    eq(t.stats?.live === null, w.stats.live === null, `live null ${i}/${j}`);
  });
});

// Unchanged rows keep their object (cheap re-render), changed ones don't.
{
  const d = new FeedClient();
  d.apply(messages[0]);
  const before = d.torrents();
  d.apply(messages[1]);
  const after = d.torrents();
  const changed = new Set((messages[1].changed ?? []).map((p) => p.id));
  eq(
    before.every((t, i) => (after[i] === t) === !changed.has(t.id)),
    true,
    "object identity follows changes",
  );
}

// Gaps: wrong base or epoch, unknown row → resync needed; state untouched.
{
  const d = new FeedClient();
  eq(d.apply(messages[1]), "gap", "delta before any snapshot");
  d.apply(messages[0]);
  eq(d.apply(messages[2]), "gap", "skipped a delta");
  eq(d.apply({ ...messages[1], epoch: "other" }), "gap", "other epoch");
  eq(d.apply({ ...messages[1], proto: 2 }), "invalid", "other protocol");
  eq(d.seq, 1, "still at the snapshot");
  eq(d.apply({ type: "heartbeat", epoch: "test", seq: 1 }), "ok", "heartbeat");
  eq(d.apply(messages[1]), "ok", "then the right delta");
}

// Formatting matches the server (Rust rounds exact ties to even).
eq(formatSpeed(0), "0.00 MiB/s", "speed 0");
eq(formatSpeed(131072), "0.12 MiB/s", "0.125 ties to even");
eq(formatSpeed(393216), "0.38 MiB/s", "0.375 ties to even");
eq(formatSpeed(1048576 * 12.5), "12.50 MiB/s", "12.5");
eq(formatSpeed(1048576 * 1234), "1234.00 MiB/s", "large");
eq(formatEta(5_400), "5s", "secs");
eq(formatEta(3_445_999), "57m 25s", "mins");
eq(formatEta(36_120_000), "10h 2m", "hours");
for (const s of snapshots)
  for (const t of s.torrents) {
    const l = t.stats.live;
    if (!l) continue;
    const bps = Math.round(l.download_speed.mbps * 1048576);
    eq(formatSpeed(bps), l.download_speed.human_readable, "fixture speed text");
  }

// Merge patch.
eq(
  applyPatch({ a: 1, b: { c: 2, d: 3 } }, { b: { c: null, e: [1] } }),
  { a: 1, b: { d: 3, e: [1] } },
  "patch",
);
eq(applyPatch({ a: { b: 1 } }, { a: 5 }), { a: 5 }, "object → scalar");
eq(applyPatch({ a: 5 }, { a: { b: 1 } }), { a: { b: 1 } }, "scalar → object");

console.log(`listFeed: ${checks - failures}/${checks} checks passed`);
if (failures) throw new Error(`${failures} listFeed check(s) failed`);
