//! Replays the server's golden feed messages (generated by the librqbit `list_feed`
//! tests from real list responses with generic names) and checks the result against
//! the full `/torrents?with_stats=true` responses, as the GPUI types read them.

use super::*;
use crate::api::ListTorrentsResponse;

pub(super) const SNAPSHOTS: &str =
    include_str!("../../../librqbit/src/list_feed/testdata/list_snapshots.json");
pub(super) const MESSAGES: &str =
    include_str!("../../../librqbit/src/list_feed/testdata/list_messages.json");

fn fixtures() -> (Vec<Value>, Vec<Value>) {
    let s: Value = serde_json::from_str(SNAPSHOTS).unwrap();
    let m: Value = serde_json::from_str(MESSAGES).unwrap();
    (
        s["snapshots"].as_array().unwrap().clone(),
        m["messages"].as_array().unwrap().clone(),
    )
}

fn full(snapshot: &Value) -> String {
    let r: ListTorrentsResponse = serde_json::from_value(snapshot.clone()).unwrap();
    debug(r.torrents)
}

/// Debug form, with speeds to 1e-12 MiB/s: serde_json's default float parser can be
/// one ulp off the exact `bps / 2^20` the feed computes.
fn debug(mut list: Vec<TorrentListItem>) -> String {
    for t in &mut list {
        if let Some(l) = t.stats.as_mut().and_then(|s| s.live.as_mut()) {
            for sp in [&mut l.download_speed, &mut l.upload_speed] {
                sp.mbps = (sp.mbps * 1e12).round() / 1e12;
            }
        }
    }
    format!("{list:#?}")
}

#[test]
fn snapshot_plus_deltas_equals_full_list() {
    let (snapshots, messages) = fixtures();
    assert_eq!(snapshots.len(), messages.len());
    let mut c = FeedClient::default();
    for (i, (m, s)) in messages.iter().zip(&snapshots).enumerate() {
        assert_eq!(c.apply(m), Apply::Updated, "message {i}");
        assert_eq!(c.seq, i as u64 + 1);
        let got = debug(c.torrents());
        let want = full(s);
        assert!(
            got == want,
            "state {i} differs:\n{}",
            first_diff(&got, &want)
        );
    }
    // Something actually changed between the states, and rows were added/removed.
    assert_ne!(full(&snapshots[0]), full(&snapshots[3]));
}

fn first_diff(a: &str, b: &str) -> String {
    for (i, (x, y)) in a.lines().zip(b.lines()).enumerate() {
        if x != y {
            return format!("line {i}: got {x:?}, want {y:?}");
        }
    }
    format!("lengths {} vs {}", a.lines().count(), b.lines().count())
}

#[test]
fn deltas_need_the_right_base() {
    let (_, messages) = fixtures();
    let mut c = FeedClient::default();
    assert_eq!(
        c.apply(&messages[1]),
        Apply::Gap,
        "delta before any snapshot"
    );
    assert_eq!(c.apply(&messages[0]), Apply::Updated);
    assert_eq!(c.apply(&messages[2]), Apply::Gap, "skipped a delta");
    assert_eq!(c.seq, 1, "a gap leaves the state alone");
    let mut other_epoch = messages[1].clone();
    other_epoch["epoch"] = "other".into();
    assert_eq!(c.apply(&other_epoch), Apply::Gap);
    assert_eq!(c.apply(&messages[1]), Apply::Updated);
    assert_eq!(
        c.apply(&serde_json::json!({"type": "heartbeat", "epoch": "x", "seq": 9})),
        Apply::Unchanged
    );
    assert_eq!(
        c.apply(&serde_json::json!({"type": "pong"})),
        Apply::Unchanged
    );
    let mut bad_proto = messages[0].clone();
    bad_proto["proto"] = 99.into();
    assert_eq!(c.apply(&bad_proto), Apply::Invalid);
    assert_eq!(
        c.apply(&serde_json::json!({"type": "what"})),
        Apply::Invalid
    );
    // A patch for an unknown row means we're out of sync.
    let mut c2 = FeedClient::default();
    c2.apply(&messages[0]);
    let bogus = serde_json::json!({"type": "delta", "proto": 1, "epoch": messages[0]["epoch"],
        "base": 1, "seq": 2, "changed": [{"id": 999_999, "name": "x"}]});
    assert_eq!(c2.apply(&bogus), Apply::Gap);
}

#[test]
fn unchanged_rows_are_not_re_expanded() {
    let (_, messages) = fixtures();
    let mut c = FeedClient::default();
    c.apply(&messages[0]);
    c.torrents();
    let n = c.expanded.len();
    assert!(n > 0);
    c.apply(&messages[1]);
    let changed = messages[1]["changed"].as_array().map_or(0, Vec::len);
    assert_eq!(c.expanded.len(), n - changed);
}

#[test]
fn formatting_matches_the_server() {
    assert_eq!(format_speed(0), "0.00 MiB/s");
    assert_eq!(format_speed(1_048_576), "1.00 MiB/s");
    assert_eq!(format_speed(5_242), "0.00 MiB/s");
    assert_eq!(format_speed(5_243), "0.01 MiB/s");
    // Exactly half a hundredth: ties to even, like Rust's {:.2}.
    assert_eq!(format_speed(131_072), "0.12 MiB/s"); // 0.125
    assert_eq!(format_speed(393_216), "0.38 MiB/s"); // 0.375
    for bps in [1u64, 999, 52_428, 52_429, 123_456_789, 10_485_760_000] {
        let want = format!("{:.2} MiB/s", bps as f64 / 1_048_576.0);
        assert_eq!(format_speed(bps), want, "{bps}");
    }
    assert_eq!(format_eta(0), "0s");
    assert_eq!(format_eta(59_999), "59s");
    assert_eq!(format_eta(61_000), "1m 1s");
    assert_eq!(format_eta(3_600_000 + 120_000 + 5_000), "1h 2m");
}

#[test]
fn inflater_reads_a_shared_deflate_stream() {
    use std::io::Write;
    // Same framing as the server: one raw deflate stream, sync-flushed per message.
    let mut enc = flate2::write::DeflateEncoder::new(Vec::new(), flate2::Compression::new(6));
    let mut frames = Vec::new();
    let msgs = [
        "{\"type\":\"pong\"}\n",
        "{\"type\":\"heartbeat\",\"epoch\":\"e\",\"seq\":1}\n{\"type\":\"pong\"}\n",
    ];
    for m in msgs {
        enc.write_all(m.as_bytes()).unwrap();
        enc.flush().unwrap();
        frames.push(std::mem::take(enc.get_mut()));
    }
    let mut inf = Inflater::default();
    let a = inf.message(&frames[0]).unwrap();
    assert_eq!(parse_lines(&a).len(), 1);
    let b = inf.message(&frames[1]).unwrap();
    let parsed: Vec<Value> = parse_lines(&b).into_iter().map(Result::unwrap).collect();
    assert_eq!(parsed.len(), 2);
    assert_eq!(parsed[0]["type"], "heartbeat");
}
